version: "3"

services:
  web:
    container_name: gowatch
    build: .
    command: /app/main
    environment:
      - PORT=80
      - GIN_MODE=release
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 80:80
